spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: ${my.db.url}
    username: ${my.db.username}
    password: ${my.db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
logging:
  level:
    sql: debug
    root: info
jwt:
  signing:
    key: 1234567890123456789012345678901234567890
server:
  port: 8080